# Generated by Django 3.2.16 on 2024-08-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created_at',), 'verbose_name': 'комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
